Controllers/ExportDataController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.IO;
using System.Linq;
using WestmeathLibraryEMS.Models;
using Microsoft.AspNetCore.Hosting;
using WestmeathLibraryEMS.ViewModels;
using System.Collections.Generic;
using System;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Threading.Tasks;
using System.Threading;
using System.Diagnostics;


namespace WestmeathLibraryEMS.Controllers
{
    public class ExportDataController : Controller
    {
        private IRepository repository;



        //variables used for reporting and filtering data result sets
        private decimal? totalCost = 0;
        private int? totalAttendees = 0;
        private int? totalMaxAttendees = 0;
        private decimal? attendeePercentage = 0;
        private int totalNumEvents = 0;
        private int totalMarketingCount = 0;
        private int posterCount = 0;
        private int facebookCount = 0;
        private int twitterCount = 0;
        private int calendarCount = 0;
        private int onlineEventCount = 0;



        private IWebHostEnvironment _hostEnvironment;


        public ExportDataController(IRepository repo, IWebHostEnvironment environment)
        {
            repository = repo;
            _hostEnvironment = environment;
        }

        public IActionResult Index()
        {
            return View();
        }


        //push excel data to the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ImportFileAsync(IFormFile file)
        {

            //import license for EPPlus
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            //get file name and path
            string wwwPath = _hostEnvironment.WebRootPath;
            string contentPath = _hostEnvironment.ContentRootPath;

            //check directory and create if it doesn't exsist
            string path = Path.Combine(_hostEnvironment.WebRootPath, "Uploads");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string fileName = Path.GetFileName(file.FileName);

            FileStream stream = null;
            GC.Collect();
            while (stream == null)
            {
                using (stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {

                    file.CopyTo(stream);
                    stream.Dispose();
                }
            }


            var excelFile = new FileInfo(@"wwwroot\Uploads\" + fileName);

            List<EventFormViewModel> excelEvents = await LoadEvents(excelFile);

            var NumberOfRetries = 3;
            var DelayOnRetry = 1000;

            for (int i = 1; i <= NumberOfRetries; ++i)
            {
                try
                {
                    stream.Close();
                    stream.Dispose();
                    GC.WaitForPendingFinalizers();
                    GC.Collect();
                    System.IO.File.Delete(@"wwwroot\Uploads\" + fileName);
                    break;
                }
                catch (IOException) when (i <= NumberOfRetries)
                {
                    Thread.Sleep(DelayOnRetry);
                }
            };

            var eventDay = repository.EventDays
                .Include(e => e.Event)
                .ToList();

            var eventMarketing = repository.EventMarketings
                .Include(e => e.Event)
                .Include(e => e.MarketingType)
                .ToList();

            var duplicateChecker = false; //check for duplicates flag variable 
            var rowCounter = 0; //row counter to display number of records inserted

            foreach (var viewModel in excelEvents)
            {

                foreach (var item in eventDay)
                {
                    if (viewModel.Event.EventName.ToLower() == item.Event.EventName.ToLower()
                        && viewModel.EventDay.EventDate == item.EventDate && viewModel.Event.VenueId == item.Event.VenueId
                        )
                        duplicateChecker = true;

                }
                if (duplicateChecker)
                {
                    continue;
                }

                if (!ModelState.IsValid)
                {
                    return RedirectToAction("New", "Events", viewModel);
                }

                if (viewModel.EventDay.Id == 0 && viewModel.Event.Id == 0)
                {

                    viewModel.Event.DateAdded = DateTime.Now;
                    viewModel.EventDay.DateAdded = DateTime.Now;



                    //Id code for events 
                    if (String.IsNullOrWhiteSpace(viewModel.Event.Guid))
                        viewModel.Event.Guid = EventsController.RandomString(8);

                    //new events that have already transpired are set to pending
                    if (viewModel.EventDay.EventStatusId == 1 && viewModel.EventDay.EventDate < DateTime.Now)
                        viewModel.EventDay.EventStatusId = 3;


                    if (viewModel.Event.Requirements == null)
                        viewModel.Event.Requirements = "no requirements";




                    if (viewModel != null)
                    {
                        repository.SaveEvent(viewModel.Event);
                        repository.CreateEvent(viewModel.Event);

                        viewModel.EventDay.EventId = viewModel.Event.Id;

                        repository.SaveEventDay(viewModel.EventDay);
                        repository.CreateEventDay(viewModel.EventDay);
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "Possible duplicate event");
                        return RedirectToAction("Error", "Shared");
                    }


                }
                rowCounter++;
            }

            ViewBag.rowCounter = rowCounter;


            return View("ImportedData", ViewBag.rowCounter);
        }


        //get events from excel
        private async Task<List<EventFormViewModel>> LoadEvents(FileInfo file)
        {

            List<EventFormViewModel> output = new List<EventFormViewModel>();

            using (ExcelPackage package = new ExcelPackage(file))
            {
                await package.LoadAsync(file);
                var ws = package.Workbook.Worksheets[1];

                int row = 2;
                int col = 1;

                while (string.IsNullOrWhiteSpace(ws.Cells[row, col].Value?.ToString()) == false)
                {
                    EventFormViewModel e = new EventFormViewModel
                    {
                        Event = new Event(),

                        EventDay = new EventDay(),

                        EventStatuses = repository.EventStatuses.ToList(),
                        EventTypes = repository.EventTypes.OrderBy(m => m.TypeName).ToList(),
                        Venues = repository.Venues.OrderBy(m => m.VenueName).ToList(),
                        Facilitators = repository.Facilitators.OrderBy(m => m.FacilitatorType).ToList()
                    };

                    var m = new EventMarketingFormViewModel
                    {
                        EventMarketing = new EventMarketing(),
                        Events = repository.Events.ToList(),
                        MarketingTypes = repository.MarketingTypes.ToList()
                    };

                    //process venue names
                    var venueName = ws.Cells[row, 1].Value.ToString().ToLower().Trim();
                    switch (venueName)
                    {
                        case "mgr":
                            e.Event.VenueId = 1;
                            break;

                        case "kln":
                            e.Event.VenueId = 2;
                            break;

                        case "kbn":
                            e.Event.VenueId = 3;
                            break;

                        case "ath":
                            e.Event.VenueId = 4;
                            break;

                        case "cpd":
                            e.Event.VenueId = 5;
                            break;

                        case "mte":
                            e.Event.VenueId = 6;
                            break;

                        default:
                            e.Event.VenueId = 1;
                            break;
                    }

                    //process event dates
                    e.EventDay.EventDate = DateTime.Parse(ws.Cells[row, col + 1].Value.ToString());

                    //process event name
                    e.Event.EventName = ws.Cells[row, col + 2].Value.ToString();

                    //process event type
                    var eventType = ws.Cells[row, col + 3].Value?.ToString().ToLower().Trim();

                    List<EventType> eventTypeInDb = repository.EventTypes.ToList();


                    foreach (var item in eventTypeInDb)
                    {

                        if (item.TypeName.ToLower() == eventType)
                        {
                            int typeId = item.Id;
                            e.Event.EventTypeId = typeId;
                            break;
                        }
                        else
                        {
                            e.Event.EventTypeId = 20;
                        }

                    }

                    //process start time
                    e.EventDay.StartTime = new TimeSpan();
                    e.EventDay.EndTime = new TimeSpan();


                    //process event description

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using WestmeathLibraryEMS.Models;
using Microsoft.EntityFrameworkCore;
using WestmeathLibraryEMS.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;


namespace WestmeathLibraryEMS.Controllers
{
    public class HomeController : Controller
    {
        private IRepository repository;
        private IHttpContextAccessor _httpContextAccessor;

        public HomeController(IRepository repo, IHttpContextAccessor httpContextAccessor)
        {
            repository = repo;
            _httpContextAccessor = httpContextAccessor;

        }



        public IActionResult Index()
        {

            CheckPendingEvents(); // check if any events are pending closure
            CheckUpcomingEvents();
            var eventDay = repository.EventDays
                            .Include(e => e.Event)
                            .Include(e => e.Event.Venue)
                            .Include(e => e.EventStatus)
                            .ToList();
            return View(eventDay);
        }

        public IActionResult NewEvent()
        {
            return RedirectToAction("New", "Events");

        }
        public IActionResult ViewEvents()
        {
            return RedirectToAction("Index", "Events");

        }

        public IActionResult Upcoming()
        {

            CheckPendingEvents();

            return RedirectToAction("UpcomingEvents", "Events");

        }

        public IActionResult Pending()
        {

            return RedirectToAction("PendingEventsStatus", "Events");

        }
        public IActionResult Canceled()
        {
            return RedirectToAction("CanceledEvents", "Events");

        }

        public IActionResult Closed()
        {
            return RedirectToAction("ClosedEvents", "Events");

        }

        public IActionResult AddEventMarketing()
        {
            return RedirectToAction("New", "EventMarketing");

        }
        public IActionResult ViewEventMarketing()
        {
            return RedirectToAction("Index", "EventMarketing");

        }


        [Authorize]
        public IActionResult SystemSetup()
        {
            return View();
        }

        [Authorize]
        public IActionResult GenerateReports()
        {
            var viewModel = new VenueEventTypeViewModel
            {
                Venues = repository.Venues.ToList(),
                EventTypes = repository.EventTypes.ToList(),
                EventStatuses = repository.EventStatuses.ToList(),
                Events = repository.Events.ToList(),
                EventDays = repository.EventDays.ToList()
            };


            return View(viewModel);
        }

        [Authorize]
        public IActionResult ViewActivityLog()
        {
            var activityLog = repository.UserActivities.ToList();
            return View(activityLog);
        }

        [HttpGet]
        public JsonResult GetEventDates()
        {

            var eventDay = repository.EventDays
                 .Include(e => e.Event)
                 .Include(e => e.Event.Venue)
                 .Include(e => e.EventStatus)
                 .ToList();

            var eventJsonList = Enumerable.Empty<object>().Select(e => new { id = Convert.ToInt64(0), title = "title", start = "start", end = "end", venue = "venue", guid = "guid", status = "status" }).ToList();

            eventJsonList.Clear();

            foreach (var item in eventDay)
            {
                eventJsonList.Add(new
                {
                    id = Convert.ToInt64(item.Event.Id),
                    title = item.Event.EventName,
                    start = item.EventDate.Date.ToString("yyyy,MM,dd"),
                    end = item.EndDate.Date.AddDays(1).ToString("yyyy,MM,dd"),// add 1 day to end for calendar to show inclusive days on the event
                    venue = item.Event.Venue.VenueName,
                    guid = item.Event.Guid,
                    status = item.EventStatus.EventStatusName
                });
            };

            string result = JsonConvert.SerializeObject(eventDay);

            Console.WriteLine(eventJsonList);

            return Json(eventJsonList);
        }

        //ensures that all closed and canceled events do not store the contact details (GDPR)

        public void CheckPendingEvents()
        {
            var events = repository.EventDays
               .Include(e => e.Event)
               .Where(e => e.EventStatus.EventStatusName == "Upcoming" && e.EndDate <= DateTime.Now)
               .ToList();

            if (events.Count != 0)
            {
                foreach (var item in events)
                {
                    item.EventStatusId = repository.EventStatuses.Where(e => e.EventStatusName == "Pending").Select(e => e.Id).SingleOrDefault();

                    repository.UpdateEventDay(item);
                    repository.CreateEventDay(item);
                }

            }

        }

        public void CheckUpcomingEvents()
        {
            var events = repository.EventDays
               .Include(e => e.Event)
               .Where(e => e.EventStatus.EventStatusName == "Pending" && e.EndDate > DateTime.Now)
               .ToList();

            if (events.Count != 0)
            {
                foreach (var item in events)
                {
                    item.EventStatusId = repository.EventStatuses.Where(e => e.EventStatusName == "Upcoming").Select(e => e.Id).SingleOrDefault();

                    repository.UpdateEventDay(item);
                    repository.CreateEventDay(item);
                }

            }
        }
        public ActionResult Help()
        {
            return View();
        }


    }
}

Views/Home/GenerateReports.cshtml
@model WestmeathLibraryEMS.ViewModels.VenueEventTypeViewModel
@{
    ViewData["Title"] = "GenerateReports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="row">
    <div class="col-12 offset-1">
        <div class="row">
            <div class="section-heading-container col-12">
                <h1 class="section-heading">Reporting Services</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-6 form-container report-form" id="divajaxCall">
                @using (Html.BeginForm("ExportDataToFile", "ExportData", FormMethod.Post))
                {
                    <div class="form-group">
                        <h4 style="color: white">Export To Excel</h4>
                        <label>
                            <input checked="checked" id="ExportExcel" name="Export"
                                   type="radio" value="Excel" hidden />

                        </label>
                    </div>


                    <p class="form-label">Select Dates: </p>
                    <div class="row form-group">

                        <div class="col-md-6">
                            <label>
                                From
                                <input class=" form-control" id="exportDateFrom" name="From" type="date" required />

                            </label>
                        </div>


                        <div class="col-md-6">
                            <label>
                                To
                                <input class=" form-control" id="exportDateTo" name="To" type="date" required />

                            </label>
                        </div>

                    </div>



                    <p class="form-label">Select Criteria: </p>

                    <div class="row">
                        <div class="col-4">
                            <lable class="form-label">Venue</lable>
                            <select class="filter form-control" id="venue" name="venue">
                                @{
                                    <option value="All">All</option>
                                    foreach (var item in Model.Venues.Select(e => e.VenueName).ToList())
                                    {
                                        <option value="@item">@item</option>
                                    }


                                }

                            </select>
                        </div>


                        <div class="col-4">
                            <lable class="form-label">Event Type</lable>
                            <select class="filter form-control" name="eventType">

                                @{

                                    <option value="All">All</option>
                                    foreach (var item in Model.EventTypes.Select(e => e.TypeName).ToList())
                                    {
                                        <option value="@item">@item</option>
                                    }


                                }

                            </select>
                        </div>

                        <div class="col-4">
                            <lable class="form-label">Event Status</lable>
                            <select class="filter form-control" name="eventStatus">

                                @{

                                    <option value="All">All</option>
                                    foreach (var item in Model.EventStatuses.Select(e => e.EventStatusName).ToList())
                                    {
                                        <option value="@item">@item</option>
                                    }


                                }

                            </select>


                        </div>

                        <div class="col-4">
                            <lable class="form-label">Ties In With</lable>
                            <select class="filter form-control" name="tiesInWith">
                                @{

                                    <option value="All">All</option>
                                    foreach (var item in Model.Events.DistinctBy(e => e.TiesInWith).Select(c => new { Id = c.Id, TiesInWith = c.TiesInWith }))
                                    {
                                        //var testString = item.Trim().ToLower();
                                        if (item != null)
                                        {

                                            <option value="@item.TiesInWith">@item.TiesInWith</option>
                                        }
                                    }

                                }
                            </select>

                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-12" style="text-align:center; padding : 5px 5px 5px 5px">
                            <button class="btn btn-primary btn-form" id="btnExportData" type="submit" value="ExportData" name="action" style="float:right">
                                Export Data
                            </button>
                        </div>
                    </div>
                }

            </div>

            <div class="col-6 form-container report-form" id="metricsForm">
                @using (Html.BeginForm("MetricsReport", "ExportData", FormMethod.Post))
                {
                    <div class="form-group">
                        <h4 style="color: white">Event Metrics</h4>

                    </div>

                    <p class="form-label">Select Dates: </p>
                    <div class="row form-group">

                        <div class="col-md-6">
                            <label>
                                From
                                <input class=" form-control" id="exportDateFrom" name="from" type="date" required />

                            </label>
                        </div>


                        <div class="col-md-6">
                            <label>
                                To
                                <input class=" form-control" id="exportDateTo" name="to" type="date" required />

                            </label>
                        </div>

                        <div class="col-md-3">
                            <lable class="form-label">Total Cost </lable>
                            <input class="form-control metrics-checkbox" type="checkbox" value="true" name="cost" id="metricsCost" />

                        </div>

                        <div class="col-md-3">
                            <lable class="form-label">Attendees </lable>
                            <input class="form-control metrics-checkbox" type="checkbox" value="true" name="attendees" id="metricsAttendees" />

                        </div>

                        <div class="col-md-3">
                            <lable class="form-label">Marketing </lable>
                            <input class="form-control metrics-checkbox" type="checkbox" value="true" name="marketing" id="metricsMarketing" />

                        </div>
                        <div class="col-md-3">
                            <lable class="form-label">Online Events</lable>
                            <input class="form-control metrics-checkbox" type="checkbox" value="true" name="online" id="metricsOnline" />

                        </div>

                    </div>

                    <p class="form-label">Select Criteria: </p>

                    <div class="row">
                        <div class="col-4">
                            <lable class="form-label">Venue</lable>
                            <select class="filter form-control" id="venue" name="venue">
                                @{
                                    <option value="All">All</option>
                                    foreach (var item in Model.Venues.Select(e => e.VenueName).ToList())
                                    {
                                        <option value="@item">@item</option>
                                    }


                                }

                            </select>
                        </div>


                        <div class="col-4">
                            <lable class="form-label">Event Type</lable>
                            <select class="filter form-control" name="eventType">

                                @{

                                    <option value="All">All</option>
                                    foreach (var item in Model.EventTypes.Select(e => e.TypeName).ToList())
                                    {
                                        <option value="@item">@item</option>
                                    }


                                }

                            </select>
                        </div>

                        <div class="col-4">
                            <lable class="form-label">Event Status</lable>
                            <select class="filter form-control" name="eventStatus">

                                @{

                                    <option value="All">All</option>
                                    foreach (var item in Model.EventStatuses.Select(e => e.EventStatusName).ToList())
                                    {
                                        <option value="@item">@item</option>
                                    }


                                }

                            </select>


                        </div>
                        <div class="col-4">
                            <lable class="form-label">Ties In With</lable>
                            <select class="filter form-control" name="tiesInWith">

                                @{

                                    <option value="All">All</option>
                                    foreach (var item in Model.Events.DistinctBy(e => e.TiesInWith).Select(c => new { Id = c.Id, TiesInWith = c.TiesInWith }))
                                    {
                                        //var testString = item.Trim().ToLower();
                                        if (item != null)
                                        {

                                            <option value="@item.TiesInWith">@item.TiesInWith</option>
                                        }
                                    }

                                }

                            </select>


                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-12" style="text-align:center; padding : 5px 5px 5px 5px">
                            <button class="btn btn-primary btn-form" id="btnExportData" type="submit" value="ExportData" name="action" style="float:right">
                                View Results
                            </button>
                        </div>
                    </div>


                }
            </div>

        </div>

        @*Generate Reports:- Importing an excel sheet*@
        @*<div class="row">
                <div class="col-6 form-container report-form" id="importForm">

                    @using (Html.BeginForm("ImportFile", "ExportData", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <h4 style="color: white">Import Excel</h4>
                        <br />
                        <div class="form-group">
                            <div class="col-md-4">
                                <label>
                                    <input id="importFile" name="file" type="file" value="Excel" required />

                                </label>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="col-md-12" style="text-align:center; padding : 5px 5px 5px 5px">
                                <button class="btn btn-primary btn-form" id="btnExportData" type="submit" value="ImportData" name="action">
                                    Import Excel Data
                                </button>
                            </div>
                        </div>



                    }
                </div>
                <div class="col-6 form-container report-form" id="importForm">

                    @using (Html.BeginForm("ImportFile", "ExportData", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <h4 style="color: white">Bookings</h4>
                        <br />
                        <div class="form-group">
                            <div class="col-md-4">
                                <label>
                                    Backup Data

                                </label>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="col-md-12" style="text-align:center; padding : 5px 5px 5px 5px">
                                <button class="btn btn-primary btn-form" id="btnExportData" type="submit" value="ImportData" name="action" disabled>
                                    Backup Data
                                </button>
                            </div>
                        </div>



                    }

                </div>

            </div>*@

        @Html.ActionLink("HOME", "Index", "Home", null, new { @class = "btn btn-info nav-back" })
        <button class="btn btn-info nav-back" onclick="goBack()">&lt--- BACK</button>
    </div>
</div>

Views/Home/ViewActivityLog.cshtml
@model IEnumerable<WestmeathLibraryEMS.Models.UserActivity>
@{
    ViewData["Title"] = "ViewActivityLog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section-heading-container col-11 offset-1">
    <h1 class="section-heading">View Activity Log</h1>
</div>

<div class="table-container col-11 offset-1 dataTableParentHidden">
    <table id="userActivityTable" class="table table-striped table-bordered display mt">
        <thead>
            <tr>
                <th>User Name</th>
                <th>Activity</th>
                <th>Date and Time</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>

                    <td class="tableDate">
                        <span>


                            @item.Date.Ticks

                        </span>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.ActionLink("HOME", "Index", "Home", null, new { @class = "btn btn-info nav-back" })
    <button class="btn btn-info nav-back" onclick="goBack()">&lt--- BACK</button>
</div>